export const TASK_DATA_REQUEST = "TASK_DATA_REQUEST" 
export const TASK_DATA_SUCCESS = "TASK_DATA_SUCCESS" 
export const TASK_DATA_FAIL = "TASK_DATA_FAIL" 

export const GET_DATA_REQUEST = "GET_DATA_REQUEST" 
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS" 
export const GET_DATA_FAIL = "GET_DATA_FAIL" 

export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST" 
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS" 
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL" 

export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST" 
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS" 
export const UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL" 